apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: redis-secrets
  namespace: sns
  files: 
    - secrets/redis/config
    - secrets/redis/password

configMapGenerator:
  - name: sns-config
    namespace: sns
    files:
      - config/config.production.json
    
resources:
- ns.yaml
- redis.yaml
- payment.yaml
- subscription.yaml