apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: redis-secrets
  namespace: sns
  files: 
    - secrets/redis/config
    - secrets/redis/password
    
resources:
- ns.yaml
- redis.yaml
- payment.yaml